title: Brandýs nad Labem-Stará Boleslav
description: Místní sdružení České pirátské strany v Brandýse nad Labem - Staré Boleslavi
lang: cs

# Permalink konfigurace pro posty - default format
permalink: /aktuality/:title/

collections:
  people:
    output: true
    permalink: /lide/:name/
  program:
    output: true
    permalink: /volby-2018/:path/
  vystavba:
    output: true
    permalink: /vystavba/:name/
  proposals:
    output: true
    permalink: /navrhy/:name/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_people"
    values:
      layout: "member"
  - scope:
      path: "_program"
    values:
      layout: "program"
  - scope:
      path: "_proposals"
    values:
      layout: "proposal"